theme = "coder" # set the theme
title = "ike.io"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[permalinks] # configure post and fixed pages permalinks
post = "blog/:title/"
default = ":title/"

[params] # theme parameters
author = "Isaac Lewis" # author's name
info = "Senior Full Stack Developer, Professional Dilletante" # author's job title or info
description = "Isaac Lewis's personal website" # site description
keywords = "blog,developer,personal" # site keywords

# Social links
[[params.social]]
name = "Github"
weight = 1
url = "https://github.com/ike/"
[[params.social]]
name = "Twitter"
weight = 2
url = "https://twitter.com/_crossdiver/"
[[params.social]]
name = "LinkedIn"
weight = 3
url = "https://www.linkedin.com/in/isaac-lewis-b16775a5/"

# Menu links
[[menu.main]]
name = "Blog"
weight = 1
url  = "/blog/"
[[menu.main]]
name = "About"
weight = 2
url = "/about/"
[[menu.main]]
name = "Quotes"
weight = 3
url = "/quotes/"
